### ISSUE TITLE
'PinMap_TIM' was not declared in this scope

### ISSUE THREAD

**Issue by S-A-L-M-A-N-A-N-S-A-R-I** [levkovigor/FastInterruptEncoder#1]
c:\Users\ABC\Documents\Arduino\libraries\FastInterruptEncoder\FastInterruptEncoder.cpp:166:91: error: 'PinMap_TIM' was not declared in this scope; did you mean 'PinMap_PWM'?

hello trying to compile it on stm32f407vgt6 with arduino2.1.1 and getting this error

**Comment by levkovigor** [comment]
@S-A-L-M-A-N-A-N-S-A-R-I didn't test it with arduino version 2

**Comment by S-A-L-M-A-N-A-N-S-A-R-I** [comment]
Ok i will try with lower versions ..on which version you were tested it?

Another thing im using board as stm32f4 series by stmicroelectonics , not by stm32duino

**Comment by S-A-L-M-A-N-A-N-S-A-R-I** [comment]
C:\Users\ABC\Documents\ArduinoData\packages\stm32duino\hardware\STM32F4\2020.5.16\cores\maple/HardwareTimer.h:200:10: note:   candidate expects 2 arguments, 1 provided
exit status 1
'TIM_TypeDef' was not declared in this scope

no luck got this on arduino 1.8.57.0

**Comment by levkovigor** [comment]
@S-A-L-M-A-N-A-N-S-A-R-I Ok I see the problem. You use inappropriate and unofficial version of stm32duino. You need to install it from here [https://github.com/stm32duino/Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32)

**Comment by S-A-L-M-A-N-A-N-S-A-R-I** [comment]
You are correct now it is working, but it is loosing steps im using it with optical encoder in the form of linear strip which has 12k line in 12inch area which means 1k steps/inch and optical sensor provides very smooth signal no bouncing checked with oscilloscope,  but still if i move it from start to end and then end to start which means 0-12000steos and 12000-0 insted of 0 it comes back to -30,-340,-79,56 so on even at slow speed , earlier i used traditional arduino attachInterrupt() to count pulse on the pin i dont know how but it was giving better performance it always returned to 0,-2,2 at slow speed , the reason to switch on this hardware method is traditional method loose steps at high speed 12k steps/sec , but it is giving even worse performance , if you know any solution please lete know

**Comment by S-A-L-M-A-N-A-N-S-A-R-I** [comment]
new update  i removed the additional timer which calls enc.loop() in example code , and calling enc.loop() in void loop() , now it works like charm always return to 0,1,-1 no matter how speedly i move  it , thanks for making this wonderful library

here is my example code now
`#include "FastInterruptEncoder.h"

Encoder enc(PA0, PA1, FULLQUAD /* or HALFQUAD or FULLQUAD */, 0. /* Noise and Debounce Filter (default 0) */); // - Example for STM32, check datasheet for possible Timers for Encoder mode. TIM_CHANNEL_1 and TIM_CHANNEL_2 only
//Encoder enc(25, 26, SINGLE, 250);  - Example for ESP32

unsigned long encodertimer = 0;

void setup() {
  Serial.begin(115200);
  
  if (enc.init()) {
    Serial.println("Encoder Initialization OK");
  } else {
    Serial.println("Encoder Initialization Failed");
    while(1);
  }


}
void loop() {      
            
  if ((millis() > (encodertimer + 1000)) || (millis() < encodertimer)) {
    Serial.println(enc.getTicks());
    encodertimer = millis();
  }
 
  enc.loop(); 
}`


i have also added setTicks() function to set the count to the value we wanted 

im leaving .cpp and .h files here so might be useful for someone
.cpp
`#include "Arduino.h"
#include "FastInterruptEncoder.h"

Encoder::Encoder(int pinA, int pinB, encoder_mode_t mode, uint8_t filter)
{
	_pinA = pinA;
	_pinB = pinB;
	_mode = mode;
	_filter = filter;
}

#if defined(ESP32)

#include <soc/pcnt_struct.h>
#include <driver/gpio.h>
#include <driver/pcnt.h>

static pcnt_isr_handle_t user_isr_handle;
pcnt_config_t r_enc_config;
pcnt_unit_t unit;

static void IRAM_ATTR pcnt_example_intr_handler(void *arg)
{
	uint32_t intr_status = PCNT.int_st.val;
	int i = 0;
	if (intr_status & (BIT(i)))
	{
		if (PCNT.status_unit[i].h_lim_lat)
		{
		}
		if (PCNT.status_unit[i].l_lim_lat)
		{
		}
		PCNT.int_clr.val = BIT(i);
	}
}

bool Encoder::init()
{
	pinMode(_pinA, INPUT_PULLUP);
	pinMode(_pinB, INPUT_PULLUP);

	unit = (pcnt_unit_t)0;

	r_enc_config.pulse_gpio_num = (gpio_num_t)_pinA;
	r_enc_config.ctrl_gpio_num = (gpio_num_t)_pinB;

	r_enc_config.unit = unit;
	r_enc_config.channel = PCNT_CHANNEL_0;

	if (_mode == SINGLE)
	{
		r_enc_config.pos_mode = PCNT_COUNT_DIS;
	}
	else
	{
		r_enc_config.pos_mode = PCNT_COUNT_DEC;
	}
	r_enc_config.neg_mode = PCNT_COUNT_INC;

	r_enc_config.lctrl_mode = PCNT_MODE_REVERSE;
	r_enc_config.hctrl_mode = PCNT_MODE_KEEP;

	r_enc_config.counter_h_lim = 32766;
	r_enc_config.counter_l_lim = -32766;

	pcnt_unit_config(&r_enc_config);

	r_enc_config.pulse_gpio_num = (gpio_num_t)_pinB;
	r_enc_config.ctrl_gpio_num = (gpio_num_t)_pinA;

	r_enc_config.unit = unit;
	r_enc_config.channel = PCNT_CHANNEL_1;

	if (_mode == FULLQUAD)
	{
		r_enc_config.pos_mode = PCNT_COUNT_DEC;
		r_enc_config.neg_mode = PCNT_COUNT_INC;
		r_enc_config.lctrl_mode = PCNT_MODE_KEEP;
		r_enc_config.hctrl_mode = PCNT_MODE_REVERSE;
	}
	else
	{
		r_enc_config.pos_mode = PCNT_COUNT_DIS;
		r_enc_config.neg_mode = PCNT_COUNT_DIS;
		r_enc_config.lctrl_mode = PCNT_MODE_DISABLE;
		r_enc_config.hctrl_mode = PCNT_MODE_DISABLE;
	}

	r_enc_config.counter_h_lim = 32766;
	r_enc_config.counter_l_lim = -32766;

	pcnt_unit_config(&r_enc_config);

	// Filter out bounces and noise
	pcnt_set_filter_value(unit, _filter);
	pcnt_filter_enable(unit);

	/* Enable events on maximum and minimum limit values */
	pcnt_event_enable(unit, PCNT_EVT_H_LIM);
	pcnt_event_enable(unit, PCNT_EVT_L_LIM);

	pcnt_counter_pause(unit); // Initial PCNT init
	pcnt_counter_clear(unit);

	/* Register ISR handler and enable interrupts for PCNT unit */
	esp_err_t er = pcnt_isr_register(pcnt_example_intr_handler, (void *)NULL, (int)0, NULL);
	if (er != ESP_OK)
	{
		return 0;
	}
	pcnt_intr_enable(unit);
	pcnt_counter_resume(unit);
	return 1;
}

void Encoder::loop()
{
	int16_t c;
	pcnt_get_counter_value(unit, &c);

	if ((_prevTicks + c) != _prevTicks)
	{
		pcnt_counter_clear(unit);
		_prevTicks = _prevTicks + c;
		if (_invert)
		{
			_ticks -= _prevTicks;
		}
		else
		{
			_ticks += _prevTicks;
		}
		_prevTicks = 0;
	}
}

#elif defined(_STM32_DEF_)

bool Encoder::init()
{
	pinMode(_pinA, INPUT_PULLUP);
	pinMode(_pinB, INPUT_PULLUP);

	pin_function(digitalPinToPinName(_pinA), pinmap_function(digitalPinToPinName(_pinA), PinMap_TIM));
	pin_function(digitalPinToPinName(_pinB), pinmap_function(digitalPinToPinName(_pinB), PinMap_TIM));

	TIM_HandleTypeDef Encoder_Handle;
	TIM_Encoder_InitTypeDef sEncoderConfig;

	Encoder_Handle.Init.Period = 65535;
	if (_mode == SINGLE)
	{
		Encoder_Handle.Init.Prescaler = 1;
	}
	else
	{
		Encoder_Handle.Init.Prescaler = 0;
	}
	Encoder_Handle.Init.ClockDivision = 0;
	Encoder_Handle.Init.CounterMode = TIM_COUNTERMODE_UP;
	Encoder_Handle.Init.RepetitionCounter = 0;
	Encoder_Handle.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

	if (_mode == FULLQUAD)
	{
		sEncoderConfig.EncoderMode = TIM_ENCODERMODE_TI12;
	}
	else
	{
		sEncoderConfig.EncoderMode = TIM_ENCODERMODE_TI1;
	}

	sEncoderConfig.IC1Polarity = TIM_ICPOLARITY_RISING;
	sEncoderConfig.IC1Selection = TIM_ICSELECTION_DIRECTTI;
	sEncoderConfig.IC1Prescaler = TIM_ICPSC_DIV1;
	sEncoderConfig.IC1Filter = _filter;

	sEncoderConfig.IC2Polarity = TIM_ICPOLARITY_RISING;
	sEncoderConfig.IC2Selection = TIM_ICSELECTION_DIRECTTI;
	sEncoderConfig.IC2Prescaler = TIM_ICPSC_DIV1;
	sEncoderConfig.IC2Filter = _filter;

	Encoder_Handle.Instance = (TIM_TypeDef *)pinmap_peripheral(digitalPinToPinName(_pinA), PinMap_TIM);
	enableTimerClock(&Encoder_Handle);
	if (HAL_TIM_Encoder_Init(&Encoder_Handle, &sEncoderConfig) != HAL_OK)
		return 0;
	HAL_TIM_Encoder_Start(&Encoder_Handle, TIM_CHANNEL_ALL);
	return 1;
}

void Encoder::loop()
{
	int c = LL_TIM_GetCounter((TIM_TypeDef *)pinmap_peripheral(digitalPinToPinName(_pinA), PinMap_TIM));
	int change = c - _prevTicks;
	_prevTicks = c;
	if (change > 40000)
	{
		change = 65535 - change;
	}
	else if (change < -40000)
	{
		change = -65535 - change;
	}
	if (_invert)
	{
		_ticks -= change;
	}
	else
	{
		_ticks += change;
	}
}

#endif

int32_t Encoder::getTicks()
{
	return _ticks;
}

void Encoder::resetTicks()
{
	_ticks = 0;
}

void Encoder::setTicks(int32_t val)
{
	_ticks = val;
}

void Encoder::setInvert(bool invert)
{
	_invert = invert;
}
`
.h
`#ifndef __FASTINTERRUPTENCODER_H__
#define __FASTINTERRUPTENCODER_H__

/******************************************************************************/
/***************************** Include Files **********************************/
/******************************************************************************/
#include "Arduino.h"

typedef enum
{
	SINGLE = 0,
	HALFQUAD = 1,
	FULLQUAD = 2,
} encoder_mode_t;

class Encoder
{
public:
	Encoder(int pinA, int pinB, encoder_mode_t mode = SINGLE, uint8_t filter = 0);
	bool init();
	void loop();
	int32_t getTicks();
	void resetTicks();
	void setTicks(int32_t val);
	void setInvert(bool invert = true);

private:
	int _pinA;
	int _pinB;
	encoder_mode_t _mode = SINGLE;
	int32_t _ticks = 0;
	int32_t _prevTicks = 0;
	uint8_t _filter = 0;
	bool _invert = false;
};

#endif // __FASTINTERRUPTENCODER_H__
`

**Comment by S-A-L-M-A-N-A-N-S-A-R-I** [comment]
new update i removed the additional timer which calls enc.loop() in example code , and calling enc.loop() in void loop() , now it works like charm always return to 0,1,-1 no matter how speedly i move it , thanks for making this wonderful library

here is my example code now
 ``` 
 #include "FastInterruptEncoder.h"

Encoder enc(PA0, PA1, FULLQUAD /* or HALFQUAD or FULLQUAD /, 0. / Noise and Debounce Filter (default 0) */); // - Example for STM32, check datasheet for possible Timers for Encoder mode. TIM_CHANNEL_1 and TIM_CHANNEL_2 only
//Encoder enc(25, 26, SINGLE, 250); - Example for ESP32

unsigned long encodertimer = 0;

void setup() {
Serial.begin(115200);

if (enc.init()) {
Serial.println("Encoder Initialization OK");
} else {
Serial.println("Encoder Initialization Failed");
while(1);
}

}
void loop() {

if ((millis() > (encodertimer + 1000)) || (millis() < encodertimer)) {
Serial.println(enc.getTicks());
encodertimer = millis();
}

enc.loop();
} 
```

i have also added setTicks() function to set the count to the value we wanted

im leaving .cpp and .h files here so might be useful for someone
.cpp
```
#include "Arduino.h"
#include "FastInterruptEncoder.h"

Encoder::Encoder(int pinA, int pinB, encoder_mode_t mode, uint8_t filter)
{
_pinA = pinA;
_pinB = pinB;
_mode = mode;
_filter = filter;
}

#if defined(ESP32)

#include <soc/pcnt_struct.h>
#include <driver/gpio.h>
#include <driver/pcnt.h>

static pcnt_isr_handle_t user_isr_handle;
pcnt_config_t r_enc_config;
pcnt_unit_t unit;

static void IRAM_ATTR pcnt_example_intr_handler(void *arg)
{
uint32_t intr_status = PCNT.int_st.val;
int i = 0;
if (intr_status & (BIT(i)))
{
if (PCNT.status_unit[i].h_lim_lat)
{
}
if (PCNT.status_unit[i].l_lim_lat)
{
}
PCNT.int_clr.val = BIT(i);
}
}

bool Encoder::init()
{
pinMode(_pinA, INPUT_PULLUP);
pinMode(_pinB, INPUT_PULLUP);

unit = (pcnt_unit_t)0;

r_enc_config.pulse_gpio_num = (gpio_num_t)_pinA;
r_enc_config.ctrl_gpio_num = (gpio_num_t)_pinB;

r_enc_config.unit = unit;
r_enc_config.channel = PCNT_CHANNEL_0;

if (_mode == SINGLE)
{
	r_enc_config.pos_mode = PCNT_COUNT_DIS;
}
else
{
	r_enc_config.pos_mode = PCNT_COUNT_DEC;
}
r_enc_config.neg_mode = PCNT_COUNT_INC;

r_enc_config.lctrl_mode = PCNT_MODE_REVERSE;
r_enc_config.hctrl_mode = PCNT_MODE_KEEP;

r_enc_config.counter_h_lim = 32766;
r_enc_config.counter_l_lim = -32766;

pcnt_unit_config(&r_enc_config);

r_enc_config.pulse_gpio_num = (gpio_num_t)_pinB;
r_enc_config.ctrl_gpio_num = (gpio_num_t)_pinA;

r_enc_config.unit = unit;
r_enc_config.channel = PCNT_CHANNEL_1;

if (_mode == FULLQUAD)
{
	r_enc_config.pos_mode = PCNT_COUNT_DEC;
	r_enc_config.neg_mode = PCNT_COUNT_INC;
	r_enc_config.lctrl_mode = PCNT_MODE_KEEP;
	r_enc_config.hctrl_mode = PCNT_MODE_REVERSE;
}
else
{
	r_enc_config.pos_mode = PCNT_COUNT_DIS;
	r_enc_config.neg_mode = PCNT_COUNT_DIS;
	r_enc_config.lctrl_mode = PCNT_MODE_DISABLE;
	r_enc_config.hctrl_mode = PCNT_MODE_DISABLE;
}

r_enc_config.counter_h_lim = 32766;
r_enc_config.counter_l_lim = -32766;

pcnt_unit_config(&r_enc_config);

// Filter out bounces and noise
pcnt_set_filter_value(unit, _filter);
pcnt_filter_enable(unit);

/* Enable events on maximum and minimum limit values */
pcnt_event_enable(unit, PCNT_EVT_H_LIM);
pcnt_event_enable(unit, PCNT_EVT_L_LIM);

pcnt_counter_pause(unit); // Initial PCNT init
pcnt_counter_clear(unit);

/* Register ISR handler and enable interrupts for PCNT unit */
esp_err_t er = pcnt_isr_register(pcnt_example_intr_handler, (void *)NULL, (int)0, NULL);
if (er != ESP_OK)
{
	return 0;
}
pcnt_intr_enable(unit);
pcnt_counter_resume(unit);
return 1;
}

void Encoder::loop()
{
int16_t c;
pcnt_get_counter_value(unit, &c);

if ((_prevTicks + c) != _prevTicks)
{
	pcnt_counter_clear(unit);
	_prevTicks = _prevTicks + c;
	if (_invert)
	{
		_ticks -= _prevTicks;
	}
	else
	{
		_ticks += _prevTicks;
	}
	_prevTicks = 0;
}
}

#elif defined(STM32_DEF)

bool Encoder::init()
{
pinMode(_pinA, INPUT_PULLUP);
pinMode(_pinB, INPUT_PULLUP);

pin_function(digitalPinToPinName(_pinA), pinmap_function(digitalPinToPinName(_pinA), PinMap_TIM));
pin_function(digitalPinToPinName(_pinB), pinmap_function(digitalPinToPinName(_pinB), PinMap_TIM));

TIM_HandleTypeDef Encoder_Handle;
TIM_Encoder_InitTypeDef sEncoderConfig;

Encoder_Handle.Init.Period = 65535;
if (_mode == SINGLE)
{
	Encoder_Handle.Init.Prescaler = 1;
}
else
{
	Encoder_Handle.Init.Prescaler = 0;
}
Encoder_Handle.Init.ClockDivision = 0;
Encoder_Handle.Init.CounterMode = TIM_COUNTERMODE_UP;
Encoder_Handle.Init.RepetitionCounter = 0;
Encoder_Handle.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

if (_mode == FULLQUAD)
{
	sEncoderConfig.EncoderMode = TIM_ENCODERMODE_TI12;
}
else
{
	sEncoderConfig.EncoderMode = TIM_ENCODERMODE_TI1;
}

sEncoderConfig.IC1Polarity = TIM_ICPOLARITY_RISING;
sEncoderConfig.IC1Selection = TIM_ICSELECTION_DIRECTTI;
sEncoderConfig.IC1Prescaler = TIM_ICPSC_DIV1;
sEncoderConfig.IC1Filter = _filter;

sEncoderConfig.IC2Polarity = TIM_ICPOLARITY_RISING;
sEncoderConfig.IC2Selection = TIM_ICSELECTION_DIRECTTI;
sEncoderConfig.IC2Prescaler = TIM_ICPSC_DIV1;
sEncoderConfig.IC2Filter = _filter;

Encoder_Handle.Instance = (TIM_TypeDef *)pinmap_peripheral(digitalPinToPinName(_pinA), PinMap_TIM);
enableTimerClock(&Encoder_Handle);
if (HAL_TIM_Encoder_Init(&Encoder_Handle, &sEncoderConfig) != HAL_OK)
	return 0;
HAL_TIM_Encoder_Start(&Encoder_Handle, TIM_CHANNEL_ALL);
return 1;
}

void Encoder::loop()
{
int c = LL_TIM_GetCounter((TIM_TypeDef *)pinmap_peripheral(digitalPinToPinName(_pinA), PinMap_TIM));
int change = c - _prevTicks;
_prevTicks = c;
if (change > 40000)
{
change = 65535 - change;
}
else if (change < -40000)
{
change = -65535 - change;
}
if (_invert)
{
_ticks -= change;
}
else
{
_ticks += change;
}
}

#endif

int32_t Encoder::getTicks()
{
return _ticks;
}

void Encoder::resetTicks()
{
_ticks = 0;
}

void Encoder::setTicks(int32_t val)
{
_ticks = val;
}

void Encoder::setInvert(bool invert)
{
_invert = invert;
}
```
.h
```
.h#ifndef FASTINTERRUPTENCODER_H
#define FASTINTERRUPTENCODER_H

/*****/
/ Include Files /
//
#include "Arduino.h"

typedef enum
{
SINGLE = 0,
HALFQUAD = 1,
FULLQUAD = 2,
} encoder_mode_t;

class Encoder
{
public:
Encoder(int pinA, int pinB, encoder_mode_t mode = SINGLE, uint8_t filter = 0);
bool init();
void loop();
int32_t getTicks();
void resetTicks();
void setTicks(int32_t val);
void setInvert(bool invert = true);

private:
int _pinA;
int _pinB;
encoder_mode_t _mode = SINGLE;
int32_t _ticks = 0;
int32_t _prevTicks = 0;
uint8_t _filter = 0;
bool _invert = false;
};

#endif // FASTINTERRUPTENCODER_H
```
