### ISSUE TITLE
Multiple encoders

### ISSUE THREAD

**Issue by paddygoat** [levkovigor/FastInterruptEncoder#2]
Really nice encoder library, although took me 2 days to find it!
It's the only one that works well on STM H723ZG.
Please could we have some instructions on how to use multiple encoders with this excellent library?
Many thanks.

**Comment by levkovigor** [comment]
@paddygoat For each encoder you should use pins with the same Timer 2-5 (TIM2, TIM3, TIM4, TIM5). One timer for one encoder. Only channels 1 or 2 are supported. Just create another instance of encoder for second encoder and duplicate all necessary code that in example. Also check STM32 documentation for your controller which timers and channels supports Encoder Mode. Usually it is TIM2 - TIM5, CH1 and CH2

**Comment by paddygoat** [comment]
That's perfect .... many thanks !!!!
