### ISSUE TITLE
Using two encoders at once - can't initialize

### ISSUE THREAD

**Issue by MagicznyHubert** [levkovigor/FastInterruptEncoder#3]
Is there any way to use two encoders with this library on ESP32? When initializing the second encoder, I get a message that I cannot do this. The code for the second encoder is the same as for the first. Is it the timer fault?

**Comment by levkovigor** [comment]
@MagicznyHubert Can't help you without looking your code

**Comment by levkovigor** [comment]
@MagicznyHubert OH, I see, it's my fault in library in part for esp32. There is initialization of pcnt unit 0. I ll try to make some corrections tomorrow.

**Comment by levkovigor** [comment]
@MagicznyHubert I've made small fix. Try release 1.0.5 but not with example esp32Interrupt, use simple.ino. Can you check it and report if it's working?

**Comment by wcliew** [comment]
Here is the output of the Serial terminal:
only encL reads and encR is always 0.

<img width="242" alt="image" src="https://github.com/levkovigor/FastInterruptEncoder/assets/8049402/550b2937-fa89-45a5-a863-c44c1f333e62">

**Comment by levkovigor** [comment]
@MagicznyHubert @wcliew  I've update library version. There are two examples with multiple encoders connected to esp32.
```
enc1.init(0);
enc2.init(1);
...
enc8,init(7);
```
8 encoders - maximum

**Comment by wcliew** [comment]
> @MagicznyHubert @wcliew I've updated library version. There are two examples with multiple encoders connected to esp32.
> 
> ```
> enc1.init(0);
> enc2.init(1);
> ...
> enc8.init(7);
> ```
> 
> 8 encoders - maximum

@levkovigor , It is working now, thank you very much for your effort!!!
<img width="235" alt="image" src="https://github.com/levkovigor/FastInterruptEncoder/assets/8049402/579c8f22-3eda-4c3e-9013-c88dc9eb5828">
